add_executable(tutorial_timer1 timer1.cpp)
target_link_libraries(tutorial_timer1 PRIVATE chaoxi::chaoxi)

add_executable(tutorial_timer3 timer3.cpp)
target_link_libraries(tutorial_timer3 PRIVATE chaoxi::chaoxi)

add_executable(tutorial_timer4 timer4.cpp)
target_link_libraries(tutorial_timer4 PRIVATE chaoxi::chaoxi)

add_executable(tutorial_timer5 timer5.cpp)
target_link_libraries(tutorial_timer5 PRIVATE chaoxi::chaoxi)

add_executable(tutorial_timer6 timer6.cpp)
target_link_libraries(tutorial_timer6 PRIVATE chaoxi::chaoxi)